---
output: html_document
editor_options: 
  chunk_output_type: console
---
# Age Differences in Coherence and Differentiation {#pcors}  
```{r edge summaries}
trait.edges.sum <- ST_net_nested %>%
  select(inventory, age, Trait, rule, gamma, edges.df) %>%
  mutate(set = "age") %>%
  group_by(inventory, set) %>%
  nest() %>%
  ungroup() %>%
  full_join(ST_net_nested_500 %>%
    select(inventory, Trait, rule, age, gamma, edges.df) %>%
    mutate(edges.df = map(edges.df, ~(.) %>% select(from, to, edge, weight = estimate))
           , gamma = paste0(".", str_remove_all(gamma, "0"))
           , set = "500") %>%
    group_by(inventory, set) %>%
    nest() %>% 
    ungroup() 
    ) %>%
  mutate(data = map(data, ~(.) %>%
                      unnest(edges.df) %>%
                      group_by(age, Trait, rule, gamma) %>%
                      summarize(mean = fisherz2r(mean(fisherz(abs(weight)), na.rm = T))) %>%
                      group_by(age, rule, gamma) %>%
                      mutate(type = "Single Trait", comp = "ST-Convergence",
                      gmean = fisherz2r(mean(fisherz(mean), na.rm = T)), 
                      traits = Trait) %>%
                      ungroup()
  )) 

trait.edges.sum50 <- trait.edges.sum %>% filter(inventory == "IPIP50") %>% unnest(data)
  
edges.sum <- MT_net_nested %>%
  select(inventory, rule, set, age, gamma, edges.df) %>%
  group_by(inventory, set, rule, gamma) %>%
  nest() %>% 
  ungroup() %>%
  full_join(MT_net_nested_500 %>%
    select(inventory, rule, set, age, gamma, edges.df) %>%
    mutate(edges.df = map(edges.df, ~(.) %>% select(from, to, edge, weight = estimate))) %>%
    group_by(inventory, set, rule, gamma) %>%
    nest() %>% 
    ungroup() %>%
    mutate(set = "500")) %>%
  mutate(data = map(data, ~(.) %>%
                      unnest(edges.df) %>%
                      separate(from, c("from_trait", "from_item"), 1) %>%
                      separate(to, c("to_trait", "to_item"), 1) %>%
                      unite(traits, from_trait, to_trait, remove = F) %>%
                      mutate(comp = ifelse(from_trait == to_trait, "Convergence", "Divergence")) %>%
                      group_by(age, traits, comp, from_trait, to_trait) %>%
                      summarize(n = n(), mean = fisherz2r(mean(fisherz(abs(weight)), na.rm = T))) %>%
                      group_by(age, from_trait, comp) %>%
                      mutate(traitMean1 = fisherz2r(mean(fisherz(mean), na.rm = T))) %>%
                      group_by(age, to_trait, comp) %>%
                      mutate(traitMean2 = fisherz2r(mean(fisherz(mean), na.rm = T))) %>%
                      ungroup() %>% 
                      mutate(traitMean = fisherz2r(rowMeans(cbind(fisherz(traitMean1), 
                                                  fisherz(traitMean2)), na.rm = T))) %>%
                      group_by(age, comp) %>%
                      mutate(type = "Multi Trait", 
                             gmean = fisherz2r(mean(fisherz(mean), na.rm = T))) %>%
                      ungroup() %>%
                      arrange(age, comp, from_trait) %>% 
                      mutate(Trait = ifelse(comp == "Convergence", toupper(from_trait), NA),
                             traitMean = rowMeans(cbind(traitMean1, traitMean2), na.rm = T))
  ))


```

```{r}
traj_plot_fun <- function(mt, inventory, rule, gamma, set){
  p <- mt %>%
    # full_join(st) %>% 
    ggplot(aes(x = as.numeric(age), y = mean)) + 
        geom_smooth(data = mt
                    , aes(group = traits)
                    , span = .3
                    , alpha = .1
                    , color = "gray"
                    , size = .2
                    , se = F) + 
        geom_smooth(data = mt
                    , size = 1
                    , aes(y = gmean, group = comp, color = comp)
                    , se = F
                    , span = .3) +
        # geom_line(data = trait.edges.sum %>% filter(inventory == "IPIP50"), 
        #           aes(group = traits), alpha = .1) + 
        # geom_line(data = trait.edges.sum %>% filter(inventory == "IPIP50"), size = 1,
        #           aes(y = gmean, group = comp,  color = comp)) + 
        scale_x_continuous(limits = c(14,80), breaks = c(seq(15,60,5), 62.5, 67.5, 72.5, 78)) +
        # scale_y_continuous(limits = c(0,.2), breaks = seq(0,.2, .05)) +
        scale_linetype_manual(values = c("solid", "dashed")) + 
        scale_color_manual(values = c("royalblue1", "mediumseagreen")) +
        labs(x = "Age", y = "Average Edge Weight",  color = NULL) + 
        # facet_grid(gamma~rule) + 
        guides(linetype = F) + 
        theme_classic() + 
        theme(axis.text.x = element_text(size = rel(.75), face = "bold", angle = 90),
              axis.text.y = element_text(face = "bold"),
              legend.key.size = unit(.4, "cm"), 
              legend.text = element_text(size = rel(.7)),
              legend.title = element_text(size = rel(.7), face = "bold"),
              legend.position = c(.15, .9))
  ggsave(p, file = sprintf("/Volumes/Emorie/projects/age nets/SAPA/02-results/01-plots/02-trajectories/png/%s-%s-%s-%s.png"
                        , inventory, rule, str_remove_all(gamma, "[.]"), set)
         , width = 5, height = 4)
  ggsave(p, file = sprintf("/Volumes/Emorie/projects/age nets/SAPA/02-results/01-plots/02-trajectories/pdf/%s-%s-%s-%s.pdf"
                        , inventory, rule, str_remove_all(gamma, "[.]"), set)
         , width = 5, height = 4)
  return(p)
}


nested_edges <- edges.sum %>% 
  # mutate(data = map(data, ~(.) %>% group_by(rule, gamma) %>% nest() %>% ungroup())) %>%
  # unnest(data) %>%
  rename(mt_data = data) %>%
  filter(set != "decades") %>%
  full_join(
    trait.edges.sum %>%
      mutate(data = map(data, ~(.) %>% group_by(rule, gamma) %>% nest() %>% ungroup())) %>%
      unnest(data) %>%
      rename(st_data = data)
    ) %>%
  # mutate(plot = pmap(list(mt_data, st_data, inventory, rule, gamma)
  mutate(plot = pmap(list(mt_data, inventory, rule, gamma, set)
              , .f = traj_plot_fun))
```


## Multi-Trait Coherence and Differentiation {#Figure1}  
```{r diff coh plots, fig.cap="Figure 1. Coherence (green) and differentiation (blue) across the lifespan. Coherence is indicated by higher average inter-item partial correlations within scales, while differentiation is indicated by lower average-inter-item partial correlations across sub-scales of the Big Five. Thus, increases in the blue differentiation line indicate decreases in differentiation and vice versa. Light gray lines show the unique trajectory for each of the Big Five."}
edges.sum %>%
  filter(inventory == "IPIP50") %>%
  unnest(data) %>%
  full_join(trait.edges.sum %>% filter(inventory == "IPIP50") %>% unnest(data)) %>% 
  ggplot(aes(x = as.numeric(age), y = mean)) + 
      geom_smooth(data = edges.sum %>% filter(inventory == "IPIP50") %>% unnest(data), span = .3,
                aes(group = traits), alpha = .1, color = "gray", size = .2, se = F) + 
      geom_smooth(data = edges.sum %>% filter(inventory == "IPIP50") %>% unnest(data), size = 1, 
                aes(y = gmean, group = comp, color = comp), se = F, span = .3) +
      # geom_line(data = trait.edges.sum %>% filter(inventory == "IPIP50"), 
      #           aes(group = traits), alpha = .1) + 
      # geom_line(data = trait.edges.sum %>% filter(inventory == "IPIP50"), size = 1,
      #           aes(y = gmean, group = comp,  color = comp)) + 
      scale_x_continuous(limits = c(14,80), breaks = c(seq(15,60,5), 62.5, 67.5, 72.5, 78)) +
      # scale_y_continuous(limits = c(0,.2), breaks = seq(0,.2, .05)) +
      scale_linetype_manual(values = c("solid", "dashed")) + 
      scale_color_manual(values = c("royalblue1", "mediumseagreen")) +
      labs(x = "Age", y = "Average Edge Weight",  color = NULL) + 
      facet_grid(gamma~rule) + 
      guides(linetype = F) + 
      theme_classic() + 
      theme(axis.text.x = element_text(size = rel(.75), face = "bold", angle = 90),
            axis.text.y = element_text(face = "bold"),
            legend.key.size = unit(.4, "cm"), 
            legend.text = element_text(size = rel(.7)),
            legend.title = element_text(size = rel(.7), face = "bold"),
            legend.position = c(.15, .9))
ggsave("/Volumes/Emorie/projects/age nets/SAPA/02-results/01-plots/02-trajectories/differentiation_coherence_line_graph_comp.png",
       width = 15, height = 8)
ggsave("/Volumes/Emorie/projects/age nets/SAPA/02-results/01-plots/02-trajectories/differentiation_coherence_line_graph_comp.pdf",
       width = 15, height = 8)
```

## Single and Mutli-Trait Coherence {#Figure2}
```{r st coherence plot, fig.cap="Figure 2. Coherence across the lifespan by trait. Solid lines indicate coherence when each trait was modeled separately, while dotted lines indicate coherence when the full IPIP-50 Big Five scale was modeled simultaneously. Coherence is indicated by higher average inter-item partial correlations within scales; thus increases in coherence across age groups suggests increasing coherence."}
big_five <- tibble(
  old = c("E", "A", "C", "N", "O")
  , new = c("Extraversion", "Agreeablessness", "Conscientiousness", "Neuroticism", "Openness")
  )

st_traj_fun <- function(mt, st, inventory, rule, gamma, set){
  st <- st %>% mutate(Trait = ifelse(is.na(Trait), str_to_upper(from_trait), str_to_upper(Trait))
                      , traits = Trait
                      , Trait = factor(Trait, levels = big_five$old, labels = big_five$new))
  mt <- mt %>% mutate(Trait = factor(Trait, levels = big_five$old, labels = big_five$new))
  p <- mt %>%
    full_join(st) %>%
    filter(comp != "Divergence") %>%
      ggplot(aes(x = as.numeric(age), y = mean, group = comp)) + 
        geom_smooth(data = filter(mt, comp == "Convergence")
                  , aes(color = Trait, linetype = type)
                  , se = F
                  , span = .5) + 
        geom_smooth(data = st
                  , aes(color = Trait, linetype = type)
                  , se = F
                  , span = .5) + 
        scale_x_continuous(limits = c(14,80), breaks = c(seq(15,60,5), 62.5, 67.5, 72.5, 78)) +
        scale_linetype_manual(values = c("dotted", "solid")) +
        guides(color = F) +
        facet_wrap(~Trait, nrow = 2) + 
        labs(x = "Age", y = "Average Edge Weight", color = "Big5\nTrait", linetype = "Network\nType") + 
        theme_classic() + 
        theme(axis.text.x = element_text(size = rel(.5), face = "bold", angle = 90),
              axis.text.y = element_text(face = "bold"),
              legend.position = c(.75,.15),
              legend.key.size = unit(.5, "cm"), 
              legend.text = element_text(size = rel(.75)),
              legend.title = element_text(size = rel(.75), face = "bold"))
  ggsave(file = sprintf("/Volumes/Emorie/projects/age nets/SAPA/02-results/01-plots/03-st-trajectories/png/%s-%s-%s-%s.png"
                        , inventory, rule, str_remove_all(gamma, "[.]"), set)
         , width = 6, height = 4)
  ggsave(file = sprintf("/Volumes/Emorie/projects/age nets/SAPA/02-results/01-plots/03-st-trajectories/pdf/%s-%s-%s-%s.pdf"
                        , inventory, rule, str_remove_all(gamma, "[.]"), set)
         , width = 6, height = 4)
  return(p)
}

nested_edges <- nested_edges %>%
  mutate(st_plot = pmap(list(mt_data, st_data, inventory, rule, gamma, set)
              , .f = possibly(st_traj_fun, NA_real_)))

(nested_edges %>% filter(rule == "median" & gamma == ".25" & inventory == "IPIP50"))$st_plot[[1]]
```

