--- 
title: "Interindividual Age Differences in Personality Structure"
author: 
  - "Emorie D Beck"
  - "David M Condon"
  - "Joshua J Jackson"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: ""
---

# Introduction  
The following site contains the code to conduct the analyses in Beck, Condon, \& Jackson (2021), which is available on Psyarxiv. 

All data and models are available as `.rdata` files on github, so the results can be reproduced without downloading the full directory or data. 

Here is the abstract:  
Most investigations in the structure of personality traits do not adequately address age; instead they presuppose a constant structure across the lifespan. Further, few studies look at the structure of personality traits a-theoretically, often neglecting to examine the relationship among indicators within a trait (coherence) and across traits (differentiation). Using a network approach, the present study examines (1) age differences in differentiation and coherence, (2) the similarity between the Big Five and network structures, and (3) the consistency of network structure across age groups in a large, cross-sectional sample. Results indicate that coherence shows early gains in adolescence with few changes across the lifespan, while differentiation mostly weakens across adulthood. The result of these age-related changes is that Big Five indicators only parallel the Big Five structure among young adults, but not older adults. The structure of young adults tends to be quite similar while the network structures of older adults appear to greatly differ from one another. These results suggest that older adults have a different structure of personality than younger adults and suggest that future research should not assume consistency in personality structure across the lifespan.  

Please address questions to edbeck@wustl.edu.